InfoWinDev.UI/Models/Entity.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace InfoWinDev.UI.Models
{
    public abstract class Entity
    {
        [Key]
        public int Id { get; set; }

        public DateTime DataCriacao { get; set; } = DateTime.Now;


    }
}

InfoWinDev.UI/Models/LoginVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InfoWinDev.UI.Models
{
    public class LoginVM
    {
        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100,ErrorMessage ="Tamanho excedido")]
        [RegularExpression(@"([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)",ErrorMessage ="Email inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100, ErrorMessage = "Tamanho excedido")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
        public bool Lembrar { get; set; }
        public string ReturnUrl { get; set; }
    }
}

InfoWinDev.UI/Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoWinDev.UI.Models
{

    [Table(nameof (Produto))]
    public class Produto:Entity
    {
       

        [Column(TypeName ="varchar(100)")]
        [Required(ErrorMessage ="Campo Obrigatório")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public int TipoProdutoId { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Column(TypeName ="money")]
        public decimal Valor { get; set; }

        [ForeignKey(nameof(TipoProdutoId))]
        public TipoProduto Tipo { get; set; }

        [Column(TypeName = "varchar(300)")]
        [StringLength(300,ErrorMessage ="Limite de Caracteres excedido.")]
        public string Descricao { get; set; }
    }
}

InfoWinDev.UI/Models/TipoProduto.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoWinDev.UI.Models
{
    [Table(nameof (TipoProduto))]
    public class TipoProduto:Entity
    {

        [Column(TypeName = "varchar(100)")]
        [Required]
        public string Nome { get; set; }

        public List<Produto> Produtos { get; set; } = new List<Produto>();

    }
}

InfoWinDev.UI/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoWinDev.UI.Models
{
    [Table("Usuário")]
    public class Usuario:Entity
    {
        [Column(TypeName = "varchar(100)")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Nome { get; set; }
        [Column(TypeName = "varchar(100)")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Email { get; set; }
        [Column(TypeName = "varchar(100)")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Senha { get; set; }

    }
}

InfoWinDev.UI/Controllers/ContaController.cs
using InfoWinDev.UI.Data;
using InfoWinDev.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using InfoWinDev.UI.Infra;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace InfoWinDev.UI.Controllers
{
    public class ContaController:Controller
    {
        private readonly InfoWinDevDataContext _ctx;
        public ContaController(InfoWinDevDataContext ctx)
        {
            _ctx = ctx;
        }

        public IActionResult Login(string returnUrl) => View(new LoginVM { ReturnUrl = returnUrl });

        [HttpPost]
        public async  Task<IActionResult> Login(LoginVM model)
        {
            var usuario = _ctx.Usuarios.FirstOrDefault(u => u.Email.ToLower() == model.Email.ToLower());

            if (usuario == null)
                ModelState.AddModelError("Email", "Email não localizado");
            else
            {
                if (usuario.Senha != model.Senha.Encrypt())
                    ModelState.AddModelError("Senha", "Senha incorreta");
                
            }

            if (ModelState.IsValid)
            {
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usuario.Email));
                identity.AddClaim(new Claim(ClaimTypes.Name, usuario.Nome));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    principal,
                    new AuthenticationProperties()
                    {
                        IsPersistent = model.Lembrar
                    }
                    );

                if (string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                {
                    return Redirect(model.ReturnUrl);
                }

                return RedirectToAction("Index", "Produtos");

            }

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }

    }
}

InfoWinDev.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InfoWinDev.UI.Controllers
{
    public class HomeController:Controller
    {

        public IActionResult Index() => View();
        
    }
}

InfoWinDev.UI/Controllers/ProdutosController.cs
using InfoWinDev.UI.Data;
using InfoWinDev.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace InfoWinDev.UI.Controllers
{
    [Authorize]
    public class ProdutosController : Controller
    {

        private readonly InfoWinDevDataContext _ctx;

        public ProdutosController(InfoWinDevDataContext ctx)
        {
            _ctx = ctx;
        }

        public IActionResult Index()
        {

            var model = _ctx.Produtos.Include(p=>p.Tipo).ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddEdit(int? id)
        {
            var tipos = _ctx.TipoProdutos.ToList().Select(t => new SelectListItem {Value = t.Id.ToString(), Text = t.Nome });
            ViewBag.Tipos = tipos;

            var model = new Produto();

            if (id != null)
            {
                model = _ctx.Produtos.Find(id);
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult AddEdit(Produto model)
        {
            if (ModelState.IsValid)
            {
                _ctx.Produtos.Add(model);
                _ctx.SaveChanges();

                 
                return RedirectToAction("Index");
            }

            var tipos = _ctx.TipoProdutos.ToList().Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Nome });
            ViewBag.Tipos = tipos;

            return View(model);
        }

        [HttpDelete]
        public IActionResult Excluir(int id)
        {
            var produto = _ctx.Produtos.Find(id);

            if (produto == null)
                return NotFound();

            _ctx.Produtos.Remove(produto);
            _ctx.SaveChanges();

            return NoContent();
        }
    }
}

InfoWinDev.UI/Controllers/TesteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InfoWinDev.UI.Controllers
{
    public class TesteController:Controller
    {

        public string Server()
        {
            return $"Bateu no teste controller - {DateTime.Now}";
        }

    }
}

InfoWinDev.UI/Views/Conta/Login.cshtml
@model LoginVM
@{
    ViewBag.Title = "Login";
}

<h2>@ViewBag.Title</h2>

<form method="post">
    <div class="form-group">
        <label>Email</label>
        <input type="type" asp-for="Email" name="nome" class="form-control" autofocus />
        <small class="is-invalid">
            <span asp-validation-for="Email"></span>
        </small>
    </div>

    <div class="form-group">
        <label>Senha</label>
        <input type="password" asp-for="Senha" name="nome" class="form-control" />
        <small class="is-invalid">
            <span asp-validation-for="Senha"></span>
        </small>
    </div>

    <div class="form-check">
        <input type="checkbox" class="form-check-input" asp-for="Lembrar">
        <label class="form-check-label" asp-for="Lembrar"></label>
    </div>

    <button class="btn btn-secondary">Entrar</button>
    <a asp-action="Index" asp-controller="Home" class="btn btn-info">Cancelar</a>

</form>

@section scripts{
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/methods_pt.js"></script>
}

InfoWinDev.UI/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Página Inicial";
}
<h2>Página inicial</h2>
<p>Seja Bem Vindo ao nosso site!</p>

InfoWinDev.UI/Views/Produtos/AddEdit.cshtml
@model Produto
@{
    ViewBag.Title = $"{(Model.Id==0?"Adicionar":"Editar")} Produto";
}

<h2>@ViewBag.Title</h2>

<form method="post">
    <div class="form-group">
        <label>Nome</label>
        <input type="type" asp-for="Nome" name="nome" class="form-control" autofocus />
        <small class="is-invalid">
            <span asp-validation-for="Nome"></span>
        </small>
    </div>

    <div class="form-group">
        <label>Tipo</label>
        <select asp-for="TipoProdutoId" asp-items="@ViewBag.Tipos" class="form-control">
            <option value="">Selecione...</option>
        </select>
        <small class="is-invalid">
            <span asp-validation-for="TipoProdutoId"></span>
        </small>
    </div>

    <div class="form-group">
        <label>Valor</label>
        <input type="type" asp-for="Valor" class="form-control" />
        <small class="is-invalid">
            <span asp-validation-for="Valor"></span>
        </small>
    </div>

    <div class="form-group">
        <label>Descrição</label>
        <textarea asp-for="Descricao" rows="4" class="form-control"></textarea>
        <small class="is-invalid">
            <span asp-validation-for="Descricao"></span>
        </small>
    </div>

    <button class="btn btn-secondary">Salvar</button>
    <a asp-action="Index" class="btn btn-info">Cancelar</a>

</form>

@section scripts{ 
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/methods_pt.js"></script>
}

InfoWinDev.UI/Views/Produtos/Index.cshtml
@model IEnumerable<Produto>
@{
    ViewBag.Title = "Listagem de Produtos";
}
<h2>@ViewBag.Title</h2>

<div>
    <a class="btn btn-success" href="@Url.Action("AddEdit")">Adicionar</a>
</div>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="item-@item.Id">
                <td>@item.Nome</td>
                <td>@item.Tipo.Nome</td>
                <td>@item.Valor</td>
                <td>
                    <a class="btn btn-warning btn-sm" asp-action="AddEdit" asp-route-id="@item.Id">Editar</a>
                    <button onclick="excluir('@item.Id','@item.Nome')" class="btn btn-danger btn-sm" >Excluir</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div data-id="0" class="modal" tabindex="-1" role="dialog" id="del-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que quer excluir o produto <strong><span id="nome-item"></span></strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="excluirConfirma">Sim</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{ 
    <script>
        function excluir(id,nome) {
            //alert('excluindo - ' + id + ' - ' + nome);
            $('#nome-item').text(nome);
            $('#del-modal').data('id',id).modal('show');

        }

        var _url = '@Url.Action("Excluir")';

        function excluirConfirma() {
            var _id = $('#del-modal').data('id');
            //alert('ok - '+ _id);
            $.ajax({
                url: _url,
                data: {id:_id},
                dataTyq: 'json',
                type: 'delete',
                success: function () {
                    toastr.success('Excluído com sucesso', 'InfoWinDev');
                },
                error: function () {
                    toastr.error('Erro ao excluir', 'InfoWinDev');
                },
                complete: function () {
                    $('#del-modal').data('id', '0').modal('hide');
                    $('#item-' + _id).remove();
                }

            });
        }
    </script>
}

InfoWinDev.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/node_modules/toastr/build/toastr.css" rel="stylesheet" />
    <title>InfoWinDev | @ViewBag.Title</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>

    @Html.Partial("_menu")

    <div class="container">
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">&copy;@DateTime.Now.Year InfoWinDev</span>
        </div>
    </footer>

    <script src="~/node_modules/jquery/dist/jquery.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/node_modules/toastr/build/toastr.min.js"></script>
    @RenderSection("scripts",false)

</body>
</html>

InfoWinDev.UI/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">InfoWinDev</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Produtos" asp-action="Index">Produtos</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Ola @User.Identity.Name
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Conta" asp-action="LogOut">Sair</a>

                    </div>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Conta" asp-action="Login">Login</a>
                </li>
            }
        </ul>
    </div>
</nav>